### PR TITLE
Added missing semi-colons to pass JSLint

### PR DESCRIPTION
**Pull request by ShashankaNataraj**
Added missing semi-colons to pass JSLint

### CODE REVIEW

**Comment by freeall** [comment]
This project uses https://github.com/feross/standard

**Comment by mafintosh** [comment]
This module uses [standard](https://github.com/feross/standard) style

**Comment by mafintosh** [comment]
I've added standard to the devDependencies to make it more clear.

**Comment by ShashankaNataraj** [comment]
Ah that explains it. TY!

**Pull request closed without merging**
