### PR TITLE
Implement ability to set volume

### PR DESCRIPTION
**Pull request by Ivshti**
Any discussion here? I don't think it's necessary.

I'll merge & publish soon

### CODE REVIEW

**Comment by mafintosh** [comment]
:+1: except this should be a minor bump. Also use `npm version minor` and then `git push && git push --tags` so we get nice release tags on github.

**Comment by mafintosh** [comment]
In general it's easier to do the version bumps on master and not in PRs

**Comment by Ivshti** [comment]
@mafintosh what do you mean 'minor'? It's 1.5.4 to 1.5.5, so it's a minor bump? What am I missing?

**Comment by Ivshti** [comment]
Minor is the y in x.y.z? That's weird

**Comment by mafintosh** [comment]
major.minor.patch yea

**Pull request merged**
